### PR TITLE
Support local interfaces

### PR DESCRIPTION
**Pull request by turowicz**
This is useful for when working with VPN that randomly assigns IP addresses to machines. The alternative is to host a local DNS server but since we have Cloudflare why bother.

### CODE REVIEW

**Comment by turowicz** [comment]
@oznu check it out

**Comment by zh99998** [comment]
+1 for this request.

**Comment by turowicz** [comment]
@zh99998 my fork works perfectly, just add the host network and the interface attributes.

**Comment by oznu** [comment]
Sorry for the delay on this, thanks for your contribution.

**Pull request merged**
